import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

const sidebars: SidebarsConfig = {
  tutorialSidebar: [
    'intro',
    {
      type: 'category',
      label: 'Product',
      items: [{type: 'autogenerated', dirName: 'product'}],
    },
    {
      type: 'category',
      label: 'Architecture',
      items: [{type: 'autogenerated', dirName: 'architecture'}],
    },
    {
      type: 'category',
      label: 'UX & Design',
      items: [{type: 'autogenerated', dirName: 'ux-design'}],
    },
    {
      type: 'category',
      label: 'Engineering',
      items: [{type: 'autogenerated', dirName: 'engineering'}],
    },
    {
      type: 'category',
      label: 'Operations',
      items: [{type: 'autogenerated', dirName: 'operations'}],
    },
    {
      type: 'category',
      label: 'Legal',
      items: [{type: 'autogenerated', dirName: 'legal'}],
    },
  ],
};

export default sidebars;
