import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

const sidebars: SidebarsConfig = {
  tutorialSidebar: [
    'intro',
    {
      type: 'category',
      label: 'Product',
      items: [{type: 'autogenerated', dirName: 'product'}],
    },
    {
      type: 'category',
      label: 'Technical',
      items: [{type: 'autogenerated', dirName: 'technical'}],
    },
    {
      type: 'category',
      label: 'Design',
      items: [{type: 'autogenerated', dirName: 'design'}],
    },
    {
      type: 'category',
      label: 'Marketing',
      items: [{type: 'autogenerated', dirName: 'marketing'}],
    },
    {
      type: 'category',
      label: 'Route to Live',
      items: [{type: 'autogenerated', dirName: 'live'}],
    },
    {
      type: 'category',
      label: 'Legal',
      items: [{type: 'autogenerated', dirName: 'legal'}],
    },
  ],
};

export default sidebars;
